### ISSUE TITLE
High priority A - Chart collapses with too many filters applied

### ISSUE THREAD

**Issue by gingerbenw** [datasciencecampus/sdg-indicators#1069]
![screen shot 2017-11-02 at 10 45 37](https://user-images.githubusercontent.com/24570483/32322038-fbc28dd2-bfba-11e7-9dcd-59f3913d421c.png)

When all of the check boxes are selected from the three drop-down boxes, the graph is replaced by the list of selections made in the adjacent combo boxes.  This list of selections also overlaps the heading that appeared above the graph, which suggests the graph may have been pushed up the page and out of sight because of the large number of selections available

**Comment by dougmet** [comment]
I don't see any easy win here except to limit the number of selections.

**Comment by gingerbenw** [comment]
I don't know if it's possible to fix the height of the chart, and cause a stupid number of filters to expand **downwards** ?

**Comment by shaneporter** [comment]
@dougmet - can we get some more clarification on limiting the number of selections? I agree it's the only way, but some more info would be great. Thanks.

**Comment by dougmet** [comment]
There are a number of ways you can go, each with its own technical challenges. This is my proposal:

You can select as many as you like. However, only the first `N` (let's say `N=20`) will display. If you've gone over 20 then a message appears with something like: "Maximum number of selections reached. Some lines will not display until you remove some."

Note for accessibility this needs to be readable by screen reader too.

The reason I like this is that it's something that the view can do without having to mess around with the DOM too much, disabling check boxes. Which is risky anyway, because you can select dozens simultaneously with select all.

**Comment by shaneporter** [comment]
OK, I'll go with 20 (but will define this in one place so it's easy to change.)

Next question is what colours/line styles should I use for the items? We were talking a while ago about grouping 'lines' from a particular disaggregation in a particular way (shades of a colour, for example), but that won't work if 20 selections are made from a single disaggregation.

I tried to look at some other ONS stuff, but couldn't find a line graph with anywhere close to 20 lines.

**Comment by shaneporter** [comment]
Also, some of the 'categories' (disaggregations) have far more than 20 options, so the 'Select all' is something of a false promise.

**Comment by dougmet** [comment]
Just to keep you on your toes. I'm wondering if we go a bit more extreme with something like 12. Then for colours we could use the exist 6 plus some dashed lines (if they're still possible).

**Comment by shaneporter** [comment]
OK
