### ISSUE TITLE
Improve home page UI

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#116]
The following have been agreed for the homepage:

- [x] Add some kind of visual hover when users mouseover the Goal images
- [x] Add some white space around each of the Goal images

**Comment by shaneporter** [comment]
Touch users don't hover. So, as long as it's understood that this shouldn't provide essential feature, then so be it.

I quite like the no-whitespace, tiled aspect of the goal images since it has harmony with the banner border

![image](https://cloud.githubusercontent.com/assets/2493614/25902974/feae20cc-3592-11e7-96d0-b316bfc5309d.png)

**Comment by nathaneastwood** [comment]
@AnnCorp and @nirenbasu - @shaneporter makes a good point. Mobile (or touch) users will not have that hover option so won't make it any more obvious you can click on the tiles.

**Comment by shaneporter** [comment]
The US uses an instruction to help:

> Click on each goal for U.S. national statistics for Sustainable Development Goal global indicators.

**Comment by AnnCorp** [comment]
@nirenbasu best to comment on this I think.  Niren is doing user testing today so could see what feedback get out of that?

**Comment by shaneporter** [comment]
Following a review from @dougmet, some changes will be pushed that address the comments in the opening issue comments made by @nathaneastwood.
