### ISSUE TITLE
Table headers are out of line

### ISSUE THREAD

**Issue by nathaneastwood** [datasciencecampus/sdg-indicators#131]
For some reason the table headers are no longer above their respective columns and are instead left aligned. I'm using Chrome 57.0.2987.133

<img width="655" alt="screen shot 2017-05-13 at 14 29 41" src="https://cloud.githubusercontent.com/assets/9799530/26025866/a4510f24-37e8-11e7-8955-f74eed5b93a0.png">

**Comment by shaneporter** [comment]
Is OK for me on 58.0.3029.110 (64-bit) - is that happening on all indicators' tables @nathaneastwood? Is it happening at a particular viewport width? Has it _just_ started happening, or can you pinpoint a version when things went awry? I did make some changes to the the headings/table widths about a week ago, so that may be the reason.

Trying to get as much info so I can investigate. Thanks!

**Comment by nathaneastwood** [comment]
I can't seem to replicate this now. Maybe it was just a loading error? It had only just started happening.

**Comment by shaneporter** [comment]
Oh OK. I have seen that issue, on my way to making some table changes, but resolved it.
