### ISSUE TITLE
Allow  more than 13 columns for disaggregation in the Table tab

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2078]
The same limit of 13 lines on the graph seems to apply to the table as well.

**Comment by AnnCorp** [comment]
In Sprint 11.  Team discussed and feel should not have same restriction on tables as charts.

**Comment by dougmet** [comment]
Might need some backend changes, right @shaneporter ? At the moment there is one representation of the filtered data set. I suppose we'd have to change this so that the chart has its own. Or at least it only processes the first `n` (`n=13`) datasets. This somewhat links to #2297 in that we might have different views of the data depending which tab you're on.

**Comment by shaneporter** [comment]
Not sure at the moment - there's code in there to restrict the dataset count, but I don't _think_ that the change for this issue will be particularly involved.

**Comment by norric1** [comment]
Checked - working as expected.
