### ISSUE TITLE
3.7.2 Not displaying

### ISSUE THREAD

**Issue by MaxEngledewAdmin** [datasciencecampus/sdg-indicators#2243]
Can't see anything wrong with the data file - it passed checks

https://datasciencecampus.github.io/sdg-indicators/3-7-2/

**Comment by dougmet** [comment]
JS error

```
Uncaught TypeError: Cannot read property 'unit' of undefined
```

Will need to dig around in this. Might result in a new data validation rule.

**Comment by dougmet** [comment]
I notice that this is the only data set that has `Units` but not other dissaggregation. So it might be something to do with that. It's columns are:

```
Year,Units,Value
```

Which is valid. But all of the others also have other columns too. There must be some assumption here that we're breaking. Suggests code changes rather than data changes.

**Comment by MaxEngledewAdmin** [comment]
As a side point this one probably should be put in as two disaggregation, without a headline, but we used the units column to ensure that some data is displayed by default. If it were possible, where there is no headline data, to display a disaggregation by default this would be the ideal situation for this indicator.

**Comment by MaxEngledewAdmin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github-Trello test](https://trello.com/c/BMUpMc2p/73-github-trello-test)
