### ISSUE TITLE
Pass html-proofer tests

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#25]
On the travis build. It's very strict!

**Comment by shaneporter** [comment]
It's generating so many errors because [html-proofer has its own issues with Jekyll's baseurl](https://github.com/gjtorikian/html-proofer/issues/266).

I don't doubt there _are_ issues in the generated markup, but they're being masked by a thunderspew of html-proofer issues.

I'm not inclined to spend too much time right now on this; I did try some 'workarounds' but they didn't work.
