### ISSUE TITLE
Trim trailing whitespace from dissaggregations

### ISSUE THREAD

**Issue by dougmet** [datasciencecampus/sdg-indicators#303]
The data import tool often sneakily adds whitespace. So sometimes you get `England` and sometimes `England     `

In the JS we need to strip trailing whitespace from dissaggregations so that they don't get detected as different values.

**Comment by shaneporter** [comment]
What do you mean by the 'data import tool'? Human (I'm not implying you've called somebody a tool) or computer, it seems that it's there that the correction should be made.

I'm saying this because although I can `trim` the whitespace, the underlying CSV is downloadable, so a 'presentation' based modification won't tackle the underlying issue, and users will have to 'tidy up' the data themselves, which isn't what we want.

Can the build reject submissions with 'problematic whitespace'?

**Comment by dougmet** [comment]
I mean prose.io

**Comment by dougmet** [comment]
Yes the build can reject, and maybe this is easier in the short term.

**Comment by dougmet** [comment]
Agreed that we will block trailing white space in the build

**Comment by dougmet** [comment]
Opening after auto close. Waiting for SDG review

**Comment by AnnCorp** [comment]
Ok to close - new data inputters will test as add more data
